# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropvariety',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.RenameField(
            model_name='crop',
            old_name='notes',
            new_name='description'
        ),
        migrations.AlterField(
            model_name='crop',
            name='description',
            field=models.TextField(blank=True)
        ),
        migrations.AlterField(
            model_name='crop',
            name='spacing',
            field=models.IntegerField(blank=True),
        ),
    ]
